# Generated by Django 3.0.7 on 2020-06-18 22:25

import custom_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20200618_2220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', custom_user.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
